spring:
  application:
    name: products_api
  datasource:
    url: jdbc:mysql://localhost:3306/tiendaapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: tchai1712
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  storage:
    path: /Users/rajb/var/data/